import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:social_media_app/core/services/supabase_database_services.dart';
import 'package:social_media_app/core/theme/app_tables_names.dart';
import 'package:social_media_app/core/models/chat_model.dart';
import 'package:social_media_app/core/models/message_model.dart';
import 'package:social_media_app/features/auth/models/user_data.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class ChatServices {
  final supabase = Supabase.instance.client;
  final dbServices = SupabaseDatabaseServices.instance;

  /// Fetches all inbox chats for the current user and populates their [otherUser] profile.
  Future<List<ChatModel>> fetchInboxChats(String currentUserId) async {
    try {
      // Fetch chats where current user is a participant
      final chatsData = await dbServices.fetchRows<ChatModel>(
        table: AppTablesNames.chats,
        builder: (data, id) => ChatModel.fromMap(data),
        filter: (query) => query.or('participant_one.eq.$currentUserId,participant_two.eq.$currentUserId'),
      );

      if (chatsData.isEmpty) return [];

      // Collect all other user IDs to fetch their profiles in a single query
      final List<String> otherUserIds = chatsData.map((chat) {
        return chat.participantOne == currentUserId ? chat.participantTwo : chat.participantOne;
      }).toList();

      // Fetch profiles of all other participants
      final List<UserData> profiles = await dbServices.fetchRows<UserData>(
        table: AppTablesNames.users,
        primaryKey: 'id',
        builder: (data, id) => UserData.fromMap(data),
        filter: (query) => query.inFilter('id', otherUserIds),
      );

      // Create a map of profiles for fast lookup
      final profileMap = {for (var p in profiles) p.id: p};

      // Map profiles back to chats
      final List<ChatModel> fullChats = chatsData.map((chat) {
        final otherId = chat.participantOne == currentUserId ? chat.participantTwo : chat.participantOne;
        return chat.copyWith(otherUser: profileMap[otherId]);
      }).toList();

      // Sort chats by last message time or update time descending
      fullChats.sort((a, b) {
        final timeA = a.lastMessageTime ?? a.updatedAt;
        final timeB = b.lastMessageTime ?? b.updatedAt;
        return timeB.compareTo(timeA);
      });

      return fullChats;
    } catch (e) {
      debugPrint('Error fetching inbox chats: $e');
      rethrow;
    }
  }

  /// Gets an existing chat or creates a new one between the current user and [otherUserId].
  Future<ChatModel> getOrCreateChat(String currentUserId, String otherUserId) async {
    try {
      // Ensure participant_one is smaller than participant_two to prevent duplicates
      final p1 = currentUserId.compareTo(otherUserId) < 0 ? currentUserId : otherUserId;
      final p2 = currentUserId.compareTo(otherUserId) < 0 ? otherUserId : currentUserId;

      // Check if chat exists
      final existingChats = await dbServices.fetchRows<ChatModel>(
        table: AppTablesNames.chats,
        builder: (data, id) => ChatModel.fromMap(data),
        filter: (query) => query.eq('participant_one', p1).eq('participant_two', p2),
      );

      // Fetch other user profile
      final otherUserList = await dbServices.fetchRows<UserData>(
        table: AppTablesNames.users,
        primaryKey: 'id',
        builder: (data, id) => UserData.fromMap(data),
        filter: (query) => query.eq('id', otherUserId),
      );
      final UserData? otherUser = otherUserList.isNotEmpty ? otherUserList.first : null;

      if (existingChats.isNotEmpty) {
        return existingChats.first.copyWith(otherUser: otherUser);
      }

      // If it doesn't exist, create it
      final newChatData = {
        'participant_one': p1,
        'participant_two': p2,
      };

      // Perform insert. We select the inserted row to get its autogenerated ID
      final inserted = await supabase
          .from(AppTablesNames.chats)
          .insert(newChatData)
          .select()
          .single();

      return ChatModel.fromMap(inserted, otherUser: otherUser);
    } catch (e) {
      debugPrint('Error getting or creating chat: $e');
      rethrow;
    }
  }

  /// Sends a message inside a chat room.
  Future<MessageModel> sendMessage({
    required String chatId,
    required String senderId,
    required String recipientId,
    required String content,
  }) async {
    try {
      final messageData = {
        'chat_id': chatId,
        'sender_id': senderId,
        'recipient_id': recipientId,
        'content': content,
        'is_read': false,
      };

      final response = await supabase
          .from(AppTablesNames.messages)
          .insert(messageData)
          .select()
          .single();

      return MessageModel.fromMap(response, response['id'] as String);
    } catch (e) {
      debugPrint('Error sending message: $e');
      rethrow;
    }
  }

  /// Uploads a chat image attachment to Supabase Storage and returns the public URL.
  Future<String> uploadChatAttachment(String filePath, String fileName) async {
    try {
      await supabase.storage
          .from('chat_attachments')
          .upload('attachments/$fileName', File(filePath));
      
      // Get public URL
      final publicUrl = supabase.storage
          .from('chat_attachments')
          .getPublicUrl('attachments/$fileName');
      
      return publicUrl;
    } catch (e) {
      debugPrint('Error uploading chat attachment: $e');
      rethrow;
    }
  }

  /// Subscribes to real-time messages in a specific chat.
  Stream<List<MessageModel>> subscribeToMessages(String chatId) {
    return dbServices.tableStream<MessageModel>(
      table: AppTablesNames.messages,
      primaryKey: ['id'],
      builder: (data, id) => MessageModel.fromMap(data, id),
      filter: (query) => query.eq('chat_id', chatId),
      sort: (a, b) => a.createdAt.compareTo(b.createdAt), // Ascending order
    );
  }

  /// Subscribes to real-time chat updates (inbox).
  /// Note: RLS automatically handles security so the user only gets their own chats.
  Stream<List<ChatModel>> subscribeToInbox() {
    return dbServices.tableStream<ChatModel>(
      table: AppTablesNames.chats,
      primaryKey: ['id'],
      builder: (data, id) => ChatModel.fromMap(data),
    );
  }

  /// Marks all messages in a chat from the other user as read.
  Future<void> markMessagesAsRead(String chatId, String currentUserId) async {
    try {
      await supabase
          .from(AppTablesNames.messages)
          .update({'is_read': true})
          .eq('chat_id', chatId)
          .eq('recipient_id', currentUserId)
          .eq('is_read', false);
    } catch (e) {
      debugPrint('Error marking messages as read: $e');
    }
  }
}
