// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBscszNmbONuhEBxht8Nb6ghRscbOeGM',
    appId: '1:827217192511:web:524abf723a49f670dffa8a',
    messagingSenderId: '827217192511',
    projectId: 'push-notifications-social-app',
    authDomain: 'push-notifications-social-app.firebaseapp.com',
    storageBucket: 'push-notifications-social-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcM394b1iAlKRw7AIaC_-lSZho9Q6O8c',
    appId: '1:827217192511:android:5995c6215b184665dffa8a',
    messagingSenderId: '827217192511',
    projectId: 'push-notifications-social-app',
    storageBucket: 'push-notifications-social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVihsDFvcCNXZEZvkdEY4PwxvkYm8udp0',
    appId: '1:827217192511:ios:8e4763cf316af37adffa8a',
    messagingSenderId: '827217192511',
    projectId: 'push-notifications-social-app',
    storageBucket: 'push-notifications-social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVihsDFvcCNXZEZvkdEY4PwxvkYm8udp0',
    appId: '1:827217192511:ios:8e4763cf316af37adffa8a',
    messagingSenderId: '827217192511',
    projectId: 'push-notifications-social-app',
    storageBucket: 'push-notifications-social-app.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdBscszNmbONuhEBxht8Nb6ghRscbOeGM',
    appId: '1:827217192511:web:45580c794e69ed68dffa8a',
    messagingSenderId: '827217192511',
    projectId: 'push-notifications-social-app',
    authDomain: 'push-notifications-social-app.firebaseapp.com',
    storageBucket: 'push-notifications-social-app.firebasestorage.app',
  );
}
